name: Deploy Google Cloud Functions

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: scholar-version2
  REGION: us-south1

jobs:
  deploy-cloud-functions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1.1.0
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Authenticate with Google Cloud using encoded JSON key
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > ${HOME}/gcloud-service-key.json
        gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json


    - name: Prepare shared code for Cloud Function search_author_id
      run: |
        cp -r ./shared ./functions/fill_publication/shared/


    - name: Deploy Cloud Function fill_publication
      run: |
        gcloud functions deploy fill_publication \
          --region ${{ env.REGION }} \
          --entry-point fill_publication \
          --runtime python312  \
          --trigger-http \
          --allow-unauthenticated \
          --gen2 \
          --memory=512MB \
          --source ./functions/fill_publication


    - name: Prepare shared code for Cloud Function search_author_id
      run: |
        cp -r ./shared ./functions/search_author_id/shared/

    - name: Deploy Cloud Function search_author_id
      run: |
        gcloud functions deploy search_author_id \
          --region ${{ env.REGION }} \
          --entry-point search_author_id \
          --runtime python312  \
          --trigger-http \
          --allow-unauthenticated \
          --timeout=3600s \
          --memory=512MB \
          --gen2 \
          --source ./functions/search_author_id/

    - name: Prepare shared code for Cloud Function find_scholar_id_from_name
      run: |
        cp -r ./shared ./functions/find_scholar_id_from_name/shared/

    - name: Deploy Cloud Function find_scholar_id_from_name
      run: |
        gcloud functions deploy find_scholar_id_from_name \
          --region ${{ env.REGION }} \
          --entry-point find_scholar_id_from_name \
          --runtime python312  \
          --trigger-http \
          --allow-unauthenticated \
          --timeout=3600s \
          --memory=512MB \
          --gen2 \
          --source ./functions/find_scholar_id_from_name/


