name: Deploy Google Cloud Functions

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: scholar-version2
  REGION: us-east1

jobs:
  deploy-cloud-functions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1.1.0
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Authenticate with Google Cloud using encoded JSON key
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > ${HOME}/gcloud-service-key.json
        gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json

    - name: Deploy Cloud Function search_author_id
      run: |
        gcloud functions deploy search_author_id \
          --region ${{ env.REGION }} \
          --entry-point search_author_id \
          --runtime python38  \
          --trigger-http \
          --allow-unauthenticated \
          --gen2 \
          --timeout=3600s \
          --source ./functions/


    - name: Deploy Cloud Function fill_publication
      run: |
        gcloud functions deploy fill_publication \
          --region ${{ env.REGION }} \
          --entry-point fill_publication \
          --runtime python38  \
          --trigger-http \
          --allow-unauthenticated \
          --gen2 \
          --source ./functions/
