name: Deploy Google Cloud Functions

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch


env:
  PROJECT_ID: scholar-version2
  REGION: us-central1
  LOCATION: $REGION
  FUNCTION_NAME: search_author_id


jobs:
  deploy-cloud-functions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1.1.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Authenticate with Google Cloud using encoded JSON key
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > ${HOME}/gcloud-service-key.json
        gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json

    - name: Deploy Cloud Function
      run: |
        gcloud functions deploy ${{ env.FUNCTION_NAME }} \
          --region ${{ env.REGION }} \
          --entry-point get_ \
          --runtime python38  \
          --trigger-http \
          --allow-unauthenticated
          --gen2
