name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to the latest version

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@latest
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and push image to Google Container Registry
      uses: google-github-actions/build-push-deploy-gcr@v1
      with:
        image_name: scholar_v2
        image_tag: latest
        registry: gcr.io/${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: scholar-service
        image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/scholar_v2:latest
        region: us-central1
        allow_unauthenticated: true
