name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Build and push image to Google Container Registry
      run: | 
        gcloud builds submit --tag gcr.io/scholar-version2/scholar_v2

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy scholar-service --image gcr.io/scholar-version2/scholar_v2 --platform managed --region us-central1 --allow-unauthenticated
