name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch


jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Authenticate with Google Cloud using encoded JSON key
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > ${HOME}/gcloud-service-key.json
        gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
    - name: Build and push image to Google Container Registry
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/scholar_v2 .
        
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy scholar-service --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/scholar_v2 --platform managed --region us-central1 --allow-unauthenticated

