name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch


jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        
    - name: Authenticate with service account
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up credentials
      run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > $HOME/gcloud-service-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud-service-key.json

    - name: Build and push image to Google Container Registry
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/scholar_v2 .

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy scholar-service \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/scholar_v2 \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
